### ISSUE TITLE
downloading flac files

### ISSUE THREAD

**Issue by robinmeier** [orcasound/orcadata#29]
i'm trying to download a file from the aws with this:

`aws --no-sign-request s3 cp s3://archive-orcasound-net/rpi_orcasound_lab/flac/2020-12-12_03-59-38_rpi_orcasound_lab--2.flac ~/orcasound.flac --storage-class STANDARD --recursive --force-glacier-transfer
`

I get no error, but file isn't being downloaded. maybe because it's in Glacier storage?

how can I access the archives?

**Comment by robinmeier** [comment]
hi, still no luck with the glacier files. 

when initiate a restore request as explained here https://aws.amazon.com/premiumsupport/knowledge-center/restore-s3-object-glacier-storage-class/

i get the following error:

aws --no-sign-request s3api restore-object --bucket archive-orcasound-net --key rpi_orcasound_lab/flac/2020-12-12_03-59-38_rpi_orcasound_lab--2.flac --restore-request '{"Days":25,"GlacierJobParameters":{"Tier":"Standard"}}'

An error occurred (AccessDenied) when calling the RestoreObject operation: Access Denied

**Comment by robinmeier** [comment]
aws --no-sign-request s3 cp s3://archive-orcasound-net/rpi_orcasound_lab/flac/2020-12-12_03-52-08_rpi_orcasound_lab--2.flac . --storage-class STANDARD --recursive --force-glacier-transfer

gives me no error but does not download the file

**Comment by scottveirs** [comment]
Yes, this probably occurred due to the Glacier storage we set up and then forgot! Sorry to not respond sooner.

Now that we have sponsored buckets from Amazon, we'll no longer use Glacier and we'll do a restore of all files into regular storage.

Please keep an eye on this new bucket -- `audio-orcasound-net` -- e.g. with:
`aws --no-sign-request s3 ls s3://audio-orcasound-net`

And updates to the access.md file in this repo.
